[project]
name = "vending-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gevent>=26.8.0",
    "google-genai>=2.19.0",
    "loguru>=0.7.3",
    "mypy>=2.3.1",
    "pydantic-settings>=2.15.0",
    "types-gevent>=26.8.0.20260811",
]
