[project]
name = "vending-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gevent>=26.8.0",
    "loguru>=0.7.3",
    "mistralai>=2.9.4",
    "mypy>=2.3.1",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "tenacity>=9.1.4",
    "types-gevent>=26.8.0.20260811",
]
